"""esquema inicial

Revision ID: 0001
Revises:
Create Date: 2026-09-29 22:08:44.826608
"""

import sqlalchemy as sa
from alembic import op

import control_almacen.db.modelos

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articulo",
        sa.Column("codigo", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("descripcion", sa.String(length=200), nullable=False),
        sa.Column("clase", sa.String(length=4), nullable=True),
        sa.Column("modelo_ax", sa.String(length=20), nullable=True),
        sa.Column("origen", sa.String(length=30), nullable=True),
        sa.Column("por_confirmar", sa.Boolean(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.CheckConstraint("clase IN ('INV', 'CONS') OR clase IS NULL"),
        sa.PrimaryKeyConstraint("codigo"),
    )
    op.create_table(
        "auditoria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fecha_hora", sa.DateTime(), nullable=False),
        sa.Column("usuario", sa.String(length=120), nullable=True),
        sa.Column("entidad", sa.String(length=40), nullable=False),
        sa.Column("entidad_id", sa.String(length=40), nullable=True),
        sa.Column("accion", sa.String(length=40), nullable=False),
        sa.Column("antes", sa.Text(), nullable=True),
        sa.Column("despues", sa.Text(), nullable=True),
        sa.Column("motivo", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config",
        sa.Column("clave", sa.String(length=60), nullable=False),
        sa.Column("valor", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("clave"),
    )
    op.create_table(
        "conteo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("descripcion", sa.String(length=200), nullable=True),
        sa.Column("usuario", sa.String(length=100), nullable=True),
        sa.Column("ultimo_folio_salida", sa.Integer(), nullable=False),
        sa.Column("ultimo_folio_entrada", sa.Integer(), nullable=False),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exportacion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("archivo", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("fecha_hora", sa.DateTime(), nullable=False),
        sa.Column("usuario", sa.String(length=120), nullable=True),
        sa.Column("ultimo_folio", sa.Integer(), nullable=True),
        sa.Column("enviado", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "persona",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("puesto", sa.String(length=120), nullable=True),
        sa.Column("area", sa.String(length=120), nullable=True),
        sa.Column("es_almacenista", sa.Boolean(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "plantilla_area",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=60), nullable=False),
        sa.Column("hoja_excel", sa.String(length=31), nullable=True),
        sa.Column("origen", sa.String(length=120), nullable=True),
        sa.Column("depto_origen", sa.String(length=120), nullable=True),
        sa.Column("destino", sa.String(length=120), nullable=True),
        sa.Column("depto_destino", sa.String(length=120), nullable=True),
        sa.Column("entrega_nombre", sa.String(length=120), nullable=True),
        sa.Column("entrega_puesto", sa.String(length=120), nullable=True),
        sa.Column("recibe_nombre", sa.String(length=120), nullable=True),
        sa.Column("recibe_puesto", sa.String(length=120), nullable=True),
        sa.Column("autoriza_nombre", sa.String(length=120), nullable=True),
        sa.Column("requiere_autoriza", sa.Boolean(), nullable=False),
        sa.Column("naturaleza", sa.String(length=20), nullable=False),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column("lote_defecto", sa.String(length=60), nullable=True),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "plantilla_excel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column("nombre_original", sa.String(length=255), nullable=False),
        sa.Column("archivo", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("registrado_en", sa.DateTime(), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ubicacion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contenedor", sa.Integer(), nullable=False),
        sa.Column("clase", sa.String(length=4), nullable=False),
        sa.Column("hoja_excel", sa.String(length=31), nullable=False),
        sa.Column("tabla_excel", sa.String(length=100), nullable=True),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hoja_excel"),
    )
    op.create_table(
        "persona_alias",
        sa.Column("alias", sa.String(length=120), nullable=False),
        sa.Column("persona_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["persona.id"],
        ),
        sa.PrimaryKeyConstraint("alias"),
    )
    op.create_table(
        "vale",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=10), nullable=False),
        sa.Column("folio", sa.Integer(), nullable=True),
        sa.Column("folio_externo", sa.String(length=40), nullable=True),
        sa.Column("estado", sa.String(length=12), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=True),
        sa.Column("origen", sa.String(length=120), nullable=True),
        sa.Column("depto_origen", sa.String(length=120), nullable=True),
        sa.Column("destino", sa.String(length=120), nullable=True),
        sa.Column("depto_destino", sa.String(length=120), nullable=True),
        sa.Column("entrego_nombre", sa.String(length=120), nullable=True),
        sa.Column("entrego_puesto", sa.String(length=120), nullable=True),
        sa.Column("recibio_nombre", sa.String(length=120), nullable=True),
        sa.Column("recibio_puesto", sa.String(length=120), nullable=True),
        sa.Column("autorizo_nombre", sa.String(length=120), nullable=True),
        sa.Column("observaciones", sa.Text(), nullable=True),
        sa.Column("plantilla_area_id", sa.Integer(), nullable=True),
        sa.Column("naturaleza", sa.String(length=20), nullable=True),
        sa.Column("creado_por", sa.String(length=120), nullable=True),
        sa.Column("creado_en", sa.DateTime(), nullable=False),
        sa.Column("emitido_en", sa.DateTime(), nullable=True),
        sa.Column("cancelado_en", sa.DateTime(), nullable=True),
        sa.Column("motivo_cancelacion", sa.Text(), nullable=True),
        sa.Column("ruta_escaneo", sa.Text(), nullable=True),
        sa.Column("migrado", sa.Boolean(), nullable=False),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.CheckConstraint("estado IN ('BORRADOR', 'EMITIDO', 'CANCELADO')"),
        sa.CheckConstraint("tipo IN ('SALIDA', 'ENTRADA')"),
        sa.ForeignKeyConstraint(
            ["plantilla_area_id"],
            ["plantilla_area.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tipo", "folio"),
    )
    op.create_table(
        "variante",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.Integer(), nullable=False),
        sa.Column("dimension", sa.String(length=200), nullable=True),
        sa.Column("np", sa.String(length=200), nullable=True),
        sa.Column("um", sa.String(length=20), nullable=False),
        sa.Column("dimension_clave", sa.String(length=200), nullable=False),
        sa.Column("np_clave", sa.String(length=200), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["codigo"],
            ["articulo.codigo"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("codigo", "dimension_clave", "np_clave", "um"),
    )
    op.create_table(
        "existencia",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("variante_id", sa.Integer(), nullable=False),
        sa.Column("ubicacion_id", sa.Integer(), nullable=False),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("item", sa.String(length=20), nullable=True),
        sa.Column(
            "cantidad_conteo", control_almacen.db.modelos.DecimalTexto(length=40), nullable=False
        ),
        sa.Column("conteo_id", sa.Integer(), nullable=True),
        sa.Column("nota", sa.Text(), nullable=True),
        sa.Column("fila_origen", sa.Integer(), nullable=True),
        sa.Column("dimension_hoja", sa.String(length=200), nullable=True),
        sa.Column("np_hoja", sa.String(length=200), nullable=True),
        sa.Column("um_hoja", sa.String(length=20), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conteo_id"],
            ["conteo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ubicacion_id"],
            ["ubicacion.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variante_id"],
            ["variante.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("existencia", schema=None) as batch_op:
        batch_op.create_index(
            "ix_existencia_ubicacion_orden", ["ubicacion_id", "orden"], unique=False
        )

    op.create_table(
        "conteo_linea",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conteo_id", sa.Integer(), nullable=False),
        sa.Column("existencia_id", sa.Integer(), nullable=False),
        sa.Column(
            "cantidad_contada", control_almacen.db.modelos.DecimalTexto(length=40), nullable=False
        ),
        sa.Column(
            "cantidad_teorica_previa",
            control_almacen.db.modelos.DecimalTexto(length=40),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["conteo_id"],
            ["conteo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["existencia_id"],
            ["existencia.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vale_linea",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vale_id", sa.Integer(), nullable=False),
        sa.Column("renglon", sa.Integer(), nullable=False),
        sa.Column("oc", sa.String(length=40), nullable=True),
        sa.Column("cantidad", control_almacen.db.modelos.DecimalTexto(length=40), nullable=True),
        sa.Column("codigo", sa.Integer(), nullable=True),
        sa.Column("descripcion", sa.String(length=200), nullable=True),
        sa.Column("clave", sa.String(length=200), nullable=True),
        sa.Column("um", sa.String(length=20), nullable=True),
        sa.Column("lote", sa.String(length=120), nullable=True),
        sa.Column("variante_id", sa.Integer(), nullable=True),
        sa.Column("existencia_id", sa.Integer(), nullable=True),
        sa.Column("no_inventariado", sa.Boolean(), nullable=False),
        sa.Column("familia", sa.String(length=20), nullable=True),
        sa.Column("transferencia_consumo", sa.String(length=20), nullable=True),
        sa.Column("encabezado_original", sa.Text(), nullable=True),
        sa.Column("fila_diario_origen", sa.Integer(), nullable=True),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["existencia_id"],
            ["existencia.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vale_id"],
            ["vale.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variante_id"],
            ["variante.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vale_linea", schema=None) as batch_op:
        batch_op.create_index("ix_vale_linea_existencia", ["existencia_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vale_linea", schema=None) as batch_op:
        batch_op.drop_index("ix_vale_linea_existencia")

    op.drop_table("vale_linea")
    op.drop_table("conteo_linea")
    with op.batch_alter_table("existencia", schema=None) as batch_op:
        batch_op.drop_index("ix_existencia_ubicacion_orden")

    op.drop_table("existencia")
    op.drop_table("variante")
    op.drop_table("vale")
    op.drop_table("persona_alias")
    op.drop_table("ubicacion")
    op.drop_table("plantilla_excel")
    op.drop_table("plantilla_area")
    op.drop_table("persona")
    op.drop_table("exportacion")
    op.drop_table("conteo")
    op.drop_table("config")
    op.drop_table("auditoria")
    op.drop_table("articulo")
    # ### end Alembic commands ###
